### ISSUE TITLE
Universal Media Downloader Freezes

### ISSUE THREAD

**Issue by bubbleflubber** [harrisonapps/Universal-Video-Downloader#1]
Quick question: Was watching a video on iPhone 6+ the other day, and the popup to download it came up, so I clicked to download. (Mind you, this particular app I had never used UMD on, so I didn't know if it would work or not.) The UMD app opened and said "Processing Files" (or something to that end) and the spinning circle looked to be working on finding the feed. Unfortunately, after about 20 minutes, UMD kept the spinning circle, with no progress. I had to force quit the app, which was no problem. However, when I came upon another video from an app that I had downloaded videos (quite successfully) with UMD, the popup came up and I chose to download. UMD opened up, but it was "frozen". It wouldn't let me enter any keyboard text, and the page froze completely. I tried another video app that UMD was successful for, but the same result happened again; UMD would open "frozen". I uninstalled the app, ran iCleaner Pro to delete any caches, found and deleted the leftover preference plist, and through iFile, pretty much got rid of anything UMD related manually. I rebooted the phone and reinstalled the app. This time, I tried again (with an app that UMD is successful with), and the initial User License Agreement page came up, so I thought I was in the clear. However, as soon as accepting the terms, the UI came up frozen again. I've had this problem before on my iPhone 5 a couple of years ago, and remembered a trick to get UMD working again, but I can't for the life of me remember now what I did. Is there a way to "reset" the app? Back to it's original condition before getting stuck on an app that it obviously did not agree with? Like I said, I'm relatively techie, and thought I got rid of all traces of the app, but for some reason, it still "freezes" immediately when I reinstall the app. I hope I was relatively thorough with the problem, but if you might provide some help, or need additional information, just let me know. Thanks so much for a wonderful app!

**Comment by harrisonapps** [comment]
The app stores things in four places:

/var/mobile/Library/Preferences/com.harrisonapps.Universal-Video-Downloader.plist for preferences
/var/mobile/Library/Universal_Video_Downloader/... for download-related files, etc.
/var/mobile/Media/Universal_Video_Downloader/... for downloaded videos
/var/mobile/Applications/(app UUID)/tmp/... for captured m3u8 index files hosted by local servers in certain apps (this seems to be a common yet undocumented practice); due to the way apps are run and sandboxed this was the best way to do it.

If you delete the first three as well as any temporary files in the /var/mobile/Applications/.../tmp directories, the app should behave as if it was a fresh install. Hope this helps with whatever debugging you may need to do -- I wrote the original code my sophomore year in high school and it is /really/ bad, so I apologize for that :p

**Comment by harrisonapps** [comment]
Oh, and apps are no longer stored in /var/mobile/Applications; now they're in /var/mobile/Containers/... but it should still store files in a given application's temporary directory (using an official API call).

**Comment by bubbleflubber** [comment]
Problem solved! Only needed Step 2 actually. Once I cleared the Downloads and Finished Downloads folders in /var/mobile/Library/Universal_Video_Downloader/, it stopped trying to access the content from the app that wasn't compatible. Your customer service is superb! I will keep this page bookmarked in case it happens again in 2 more years... ha! Thanks again so much for your help. Easy fix with iFile, and it's back up and running without a hitch! Cheers!

**Comment by harrisonapps** [comment]
Glad I could help!
